### PR TITLE
SYN-3798: add new filters

### PR DESCRIPTION
**Pull request by bchhay-splunk**

### CODE REVIEW

**Review by greatestusername-splunk — CHANGES_REQUESTED** [review]
Mind updating the tests for [`get_checksv2_test`](https://github.com/splunk/syntheticsclient/blob/v2/syntheticsclientv2/get_checksv2_test.go) then running `make testacc` and pasted in this PR?

I have yet to add the tests to the pipeline for this repo 🤦

**Comment by greatestusername** [comment]
@bchhay-splunk would you mind closing this PR and opening it against the `v2` branch? To release we'll need it in the `v2` branch either way.
Also it will re-trigger the new CI checks in the workflow.
Thanks!

**Comment by greatestusername-splunk** [comment]
@bchhay-splunk would you mind closing this PR and opening it against the `v2` branch? To release we'll need it in the `v2` branch either way.
Also it will re-trigger the new CI checks in the workflow.
Thanks!

**Comment by bchhay-splunk** [comment]
> @bchhay-splunk would you mind closing this PR and opening it against the `v2` branch? To release we'll need it in the `v2` branch either way. Also it will re-trigger the new CI checks in the workflow. Thanks!

will do! thanks

**Pull request closed without merging**
