### PR TITLE
SYN-3741: Add automaticRetries to the synthetics /test API

### PR DESCRIPTION
**Pull request by kparvin**
This MR adds the automaticRetries attribute to all test types.

Resolves SYN-3741

----

### Before the change?

* `automaticRetries` field just defaulted to 0

### After the change?

* Users can set the `automaticRetries` field on any test to 1 or 0

### Pull request checklist 
- [x] Acceptance Tests have been updated, run (`make testacc`), and pasted in this PR (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

#### Acceptance Test Output

```
PASS
coverage: 70.7% of statements
ok  	github.com/splunk/syntheticsclient/v2/syntheticsclientv2	1.795s	coverage: 70.7% of statements
```

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by kparvin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kparvin** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by kparvin** [comment]
@greatestusername-splunk Can you review this MR? For some reason github won't let me assign a reviewing in the UI.

**Review by greatestusername-splunk — APPROVED** [review]
LGTM

**Pull request merged**
