### PR TITLE
SYN-4427: Add omitempty field for WaitForNavTimeout

### PR DESCRIPTION
**Pull request by nitun-splunk**
Resolves #ISSUE_NUMBER

----

### Before the change?

*  WaitForNavTimeout was default set to 0 if we set it to null or remove this field, which cause immidiate timeout

### After the change?

* this will set filed to null or empty after this changes.

### Pull request checklist 
- [ ] Acceptance Tests have been updated, run (`make testacc`), and pasted in this PR (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

#### Acceptance Test Output

```

```

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

----

### CODE REVIEW

**Comment by nitun-splunk** [comment]
recheck

**Comment by nitun-splunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nitun-splunk** [comment]
recheck

**Comment by nitun-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Review by sangn-splunk — APPROVED** [review]

**Pull request merged**
